message:
  reload: "Config reloaded!"
  stop: "Room system stopped!"
  start: "Room system started!"
  reset: "Config reset!"
  save: "Config saved!"
  getItem: "아이템을 지급하였습니다."
  spawn: "스폰으로 이동하였습니다."